"""
Configuration Generator Module.

Generates MoMo configuration files from wizard data:
- momo.yml (main config)
- network configuration
- Nexus connection settings
"""

from __future__ import annotations

import logging
import secrets
from datetime import datetime
from pathlib import Path
from typing import Optional

import yaml

logger = logging.getLogger(__name__)


class ConfigGenerator:
    """
    Generates MoMo configuration from wizard data.
    
    Creates all necessary configuration files for MoMo to run
    after the first boot wizard completes.
    """
    
    # Default paths
    CONFIG_DIR = Path("/etc/momo")
    MOMO_CONFIG = Path("/etc/momo/momo.yml")
    NETWORK_CONFIG = Path("/etc/momo/network.yml")
    NEXUS_CONFIG = Path("/etc/momo/nexus.yml")
    SETUP_COMPLETE_FLAG = Path("/etc/momo/.setup_complete")
    
    def __init__(
        self,
        config_dir: Optional[Path] = None,
    ):
        """
        Initialize config generator.
        
        Args:
            config_dir: Base directory for config files
        """
        self.config_dir = config_dir or self.CONFIG_DIR
        self.momo_config = self.config_dir / "momo.yml"
        self.network_config = self.config_dir / "network.yml"
        self.nexus_config = self.config_dir / "nexus.yml"
        self.setup_complete_flag = self.config_dir / ".setup_complete"
    
    async def generate(self, wizard_data: dict) -> bool:
        """
        Generate all configuration files from wizard data.
        
        Args:
            wizard_data: Data collected from wizard steps
            
        Returns:
            True if successful, False otherwise
        """
        try:
            # Try primary config dir, fallback to alternative
            try:
                self.config_dir.mkdir(parents=True, exist_ok=True)
            except PermissionError:
                # Fallback to /opt/momo/configs
                alt_dir = Path("/opt/momo/configs")
                logger.warning(f"Cannot write to {self.config_dir}, falling back to {alt_dir}")
                self.config_dir = alt_dir
                self.momo_config = alt_dir / "momo.yml"
                self.network_config = alt_dir / "network.yml"
                self.nexus_config = alt_dir / "nexus.yml"
                self.setup_complete_flag = alt_dir / ".setup_complete"
                self.config_dir.mkdir(parents=True, exist_ok=True)
            
            # Generate main config
            momo_config = self._generate_momo_config(wizard_data)
            self._write_yaml(self.momo_config, momo_config)
            logger.info(f"Wrote main config to {self.momo_config}")
            
            # Generate network config
            if "network" in wizard_data:
                network_config = self._generate_network_config(wizard_data)
                self._write_yaml(self.network_config, network_config)
                logger.info(f"Wrote network config to {self.network_config}")
            
            # Generate Nexus config
            if wizard_data.get("nexus", {}).get("enabled"):
                nexus_config = self._generate_nexus_config(wizard_data)
                self._write_yaml(self.nexus_config, nexus_config)
                logger.info(f"Wrote nexus config to {self.nexus_config}")
            
            # Mark setup as complete
            self.setup_complete_flag.touch()
            logger.info(f"Created setup complete flag: {self.setup_complete_flag}")
            
            logger.info("Configuration generated successfully")
            return True
            
        except PermissionError as e:
            logger.error(f"Permission denied writing config: {e}")
            raise  # Re-raise to let caller handle
        except Exception as e:
            logger.error(f"Failed to generate config: {e}", exc_info=True)
            return False
    
    def _generate_momo_config(self, wizard_data: dict) -> dict:
        """Generate main momo.yml configuration."""
        
        # Map profile to mode
        profile = wizard_data.get("profile", "balanced")
        mode_map = {
            "passive": "passive",
            "balanced": "auto",
            "aggressive": "aggressive",
        }
        
        # Generate API token
        api_token = secrets.token_urlsafe(32)
        
        config = {
            # Header comment
            "_comment": f"Generated by First Boot Wizard on {datetime.now().isoformat()}",
            
            # Mode
            "mode": mode_map.get(profile, "auto"),
            
            # Interface
            "interface": {
                "name": "wlan1",  # Attack interface (not management)
                "channels": list(range(1, 14)),
                "channel_hop": True,
                "hop_interval": 0.5,
                "mac_randomization": True,
                "regulatory_domain": "TR",
            },
            
            # Web interface
            "web": {
                "enabled": True,
                "host": "0.0.0.0",
                "port": 8082,
                "allow_delete": False,
                "require_auth": True,
                "title": "MoMo Dashboard",
            },
            
            # Security
            "security": {
                "api_token": api_token,
                "admin_password_hash": wizard_data.get("admin_password_hash", ""),
            },
            
            # Logging
            "logging": {
                "level": "INFO",
                "base_dir": "/var/log/momo",
                "rotation": "50MB",
                "max_files": 10,
            },
            
            # Capture settings
            "capture": {
                "enabled": True,
                "out_dir_name": "handshakes",
                "max_cap_size": "100MB",
                "auto_convert_22000": True,
            },
            
            # Aggressive mode settings (based on profile)
            "aggressive": {
                "enabled": profile == "aggressive",
                "deauth_enabled": profile == "aggressive",
                "max_deauth_per_min": 30 if profile == "aggressive" else 10,
                "min_rssi": -70,
            },
            
            # Plugins
            "plugins": {
                "enabled": self._get_plugins_for_profile(profile),
                "disabled": [],
            },
            
            # Language
            "language": wizard_data.get("language", "en"),
        }
        
        # Add whitelist if provided
        if wizard_data.get("whitelist"):
            config["whitelist"] = {
                "ssids": wizard_data["whitelist"].get("ssids", []),
                "bssids": wizard_data["whitelist"].get("bssids", []),
            }
        
        return config
    
    def _generate_network_config(self, wizard_data: dict) -> dict:
        """Generate network configuration."""
        
        network = wizard_data.get("network", {})
        mode = network.get("mode", "ap")
        
        config = {
            "_comment": "MoMo Management Network Configuration",
            
            "mode": mode,
            
            "management_interface": "wlan0",  # Built-in WiFi
            
            "ap": {
                "ssid": network.get("ap", {}).get("ssid", "MoMo-Management"),
                "password": network.get("ap", {}).get("password", ""),
                "channel": network.get("ap", {}).get("channel", 6),
                "hidden": False,
                "ip_address": "192.168.4.1",
                "dhcp_start": "192.168.4.10",
                "dhcp_end": "192.168.4.50",
            },
            
            "client": {
                "ssid": network.get("client", {}).get("ssid", ""),
                "password": network.get("client", {}).get("password", ""),
                "auto_reconnect": True,
            },
            
            "ssh": {
                "enabled": True,
                "port": 22,
            },
        }
        
        return config
    
    def _generate_nexus_config(self, wizard_data: dict) -> dict:
        """Generate Nexus connection configuration."""
        
        nexus = wizard_data.get("nexus", {})
        
        config = {
            "_comment": "MoMo Nexus Connection Configuration",
            
            "enabled": nexus.get("enabled", False),
            "url": nexus.get("url", ""),
            "device_id": nexus.get("device_id", ""),
            "device_name": nexus.get("device_name", ""),
            "api_key": nexus.get("api_key", ""),
            
            "sync": {
                "enabled": True,
                "interval": 30,
                "handshakes": True,
                "credentials": True,
                "wardriving": True,
                "stats": True,
            },
            
            "cloud_crack": {
                "enabled": True,
                "auto_submit": True,
                "notify_on_crack": True,
            },
            
            "alerts": {
                "forward_to_nexus": True,
                "receive_commands": True,
            },
        }
        
        return config
    
    def _get_plugins_for_profile(self, profile: str) -> list[str]:
        """Get recommended plugins for profile."""
        
        # Base plugins (always enabled)
        base_plugins = [
            "wardriver",
            "gps",
            "auto_backup",
            "oled_status",
        ]
        
        # Profile-specific plugins
        profile_plugins = {
            "passive": [
                "ble_scanner",
            ],
            "balanced": [
                "ble_scanner",
                "capture",
                "cracker",
            ],
            "aggressive": [
                "ble_scanner",
                "capture",
                "cracker",
                "evil_twin",
                "karma_mana",
                "creds_harvester",
            ],
        }
        
        return base_plugins + profile_plugins.get(profile, [])
    
    def _write_yaml(self, path: Path, data: dict):
        """Write YAML file with proper formatting."""
        
        # Custom representer for better formatting
        def str_representer(dumper, data):
            if "\n" in data:
                return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
            return dumper.represent_scalar("tag:yaml.org,2002:str", data)
        
        yaml.add_representer(str, str_representer)
        
        with open(path, "w", encoding="utf-8") as f:
            yaml.dump(
                data,
                f,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
                indent=2,
            )
        
        # Set permissions (readable by owner only for sensitive files)
        path.chmod(0o600)
        
        logger.info(f"Wrote config to {path}")
    
    def validate_wizard_data(self, data: dict) -> tuple[bool, list[str]]:
        """
        Validate wizard data before generating config.
        
        Args:
            data: Wizard data to validate
            
        Returns:
            Tuple of (is_valid, list of errors)
        """
        errors = []
        
        # Check required fields
        if not data.get("admin_password_hash"):
            errors.append("Admin password is required")
        
        if not data.get("language"):
            data["language"] = "en"  # Default
        
        if not data.get("profile"):
            data["profile"] = "balanced"  # Default
        
        # Validate network config
        network = data.get("network", {})
        mode = network.get("mode", "ap")
        
        if mode == "ap":
            ap_password = network.get("ap", {}).get("password", "")
            if len(ap_password) < 8:
                errors.append("AP password must be at least 8 characters")
        elif mode == "client":
            if not network.get("client", {}).get("ssid"):
                errors.append("Client SSID is required in client mode")
        
        # Validate Nexus config if enabled
        nexus = data.get("nexus", {})
        if nexus.get("enabled"):
            if not nexus.get("url"):
                errors.append("Nexus URL is required when Nexus is enabled")
        
        return len(errors) == 0, errors
    
    def load_existing_config(self) -> Optional[dict]:
        """
        Load existing configuration if available.
        
        Returns:
            Existing config dict or None
        """
        if self.momo_config.exists():
            try:
                with open(self.momo_config, "r", encoding="utf-8") as f:
                    return yaml.safe_load(f)
            except Exception as e:
                logger.warning(f"Failed to load existing config: {e}")
        return None

