name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip
          pip install build hatch-vcs
          python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: momo-dist
          path: dist/*

